# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b34959b393e0984ac85021b60d4c969e"
application_url = "https://north-standard-html-sitemap.vercel.app"
embedded = true
name = "Standard HTML Sitemap"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_online_store_navigation,read_products,read_content,write_content"
optional_scopes = ["read_legal_policies"]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://north-standard-html-sitemap.vercel.app/auth/callback",
  "https://north-standard-html-sitemap.vercel.app/auth/shopify/callback",
  "https://north-standard-html-sitemap.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete", "collections/create", "collections/update", "collections/delete"]
uri = "/webhooks/sitemap/changed"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks/compliance"

[app_proxy]
url = "https://north-standard-html-sitemap.vercel.app/proxy/html-sitemap"
subpath = "html-sitemap"
prefix = "apps"
