# This file stores configurations for your Shopify app.
client_id = ""
name = "Dynamic HTML Sitemap"
handle = "dynamic-html-sitemap"
application_url = "https://north-standard-html-sitemap.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[access_scopes]
scopes = "read_products,read_content,write_content,read_online_store_navigation,write_app_proxy"

[auth]
redirect_urls = [
  "https://north-standard-html-sitemap.vercel.app/auth/callback",
  "https://north-standard-html-sitemap.vercel.app/auth/shopify/callback",
  "https://north-standard-html-sitemap.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete", "collections/create", "collections/update", "collections/delete", "pages/create", "pages/update", "pages/delete", "articles/create", "articles/update", "articles/delete"]
uri = "/webhooks/sitemap/changed"

[app_proxy]
url = "/proxy/html-sitemap"
prefix = "apps"
subpath = "html-sitemap"

[pos]
embedded = false
